name: Deploy on push

on:
    push:
        branches:
            - main

jobs:
    trigger-versal:
        runs-on: ubuntu-latest
        steps:
          - name: Calling Vercel Deploy hook
            run: curl -s -X GET "${{secrets.HUME_VERCEL_DEPLOY_HOOK_URL}}"